# Display a box
print("Please enter a character for the eye")
eye = input()
print("Beep's expression is now as follow:")
print("##########")
print("#  " + eye ,"", eye + "  #")
print("#  ----  #")
print("##########")
print("    ##    ")
print("$$######$$")
print("$ #    # $")
print("$ #    # $")
print("  $$##$$  ")
print("  $$  $$  ")
print("  $$  $$  ")  