print("Stop! What is your name and why are you here?")
name = input()
print("You are trespassing " + name + ", this is a dangerous place!!!\nCan't you read the sign?\n")
print("########################################################")
print("########################################################")
print("####                                                ####")
print("####     ######  ##########   #######    #######    ####")
print("####    ##           ##      ##     ##   ##    ##   ####")
print("####    ######       ##      ##     ##   ##    ##   ####")
print("####        ##       ##      ##     ##   #######    ####")
print("####        ##       ##      ##     ##   ##         ####")
print("####   ######        ##       #######    ##         ####")
print("####                                                ####")
print("########################################################")
print("######### \"NO TRESPASSING BEYOND THIS POINT!!!\" ########")
print("########################################################")
"\n"
print("Choose a direction")
