print("Please enter the number of lives: ")
number_lives = int(input())
print("Please enter the energy level: ")
energy_level = int(input())
print("Please enter the shield level: ")
shield_level = int(input())
print("Health has been set.")
print("Lives: " + number_lives * (" \u2764"))
print("Energy: " + energy_level * (" \u2726"))
print("Shield: " + shield_level * (" \u2726")) 